server.port: 8001

spring:
  application.name: spring-cloud-config-config
  cloud:
    config:
      server:
        git:
          # git 仓库地址
          uri: https://github.com/Al-assad/spring-cloud-sample
          # git 地址下的相对目录，多个使用 , 分隔
          search-paths: spring-cloud-config/config-repo
          username: helloworld@sample.com
          password: 123
