server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: github_route
          uri: https://github.com/Al-assad/spring-cloud-sample
          predicates:
            - Path=/github

  #      - id: time_route
  #        uri: https://github.com/Al-assad/spring-cloud-sample
  #        predicates:
  #        - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
  #        - Before=2018-01-20T06:06:06+08:00[Asia/Shanghai]
  #        - Between=2018-01-20T06:06:06+08:00[Asia/Shanghai], 2019-01-20T06:06:06+08:00[Asia/Shanghai]
  #      - id: cookie_route
  #        uri: https://github.com/Al-assad/spring-cloud-sample
  #        predicates:
  #        - Cookie=assad, kee.e
  #      - id: header_route
  #        uri: https://github.com/Al-assad/spring-cloud-sample
  #        predicates:
  #        - Header=X-Request-Id, \d+
  #      - id: host_route
  #        uri: https://github.com/Al-assad/spring-cloud-sample
  #        predicates:
  #        - Host=**.assad.site
  #      - id: method_route
  #        uri: https://github.com/Al-assad/spring-cloud-sample
  #        predicates:
  #        - Method=GET
  #      - id: host_route
  #        uri: https://github.com/Al-assad/spring-cloud-sample
  #        predicates:
  #        - Path=/foo/{segment}
  #      - id: query_route
  #        uri: https://github.com/Al-assad/spring-cloud-sample
  #        predicates:
  #         - Query=keep, pu.
  #      - id: remoteaddr_route
  #        uri: https://github.com/Al-assad/spring-cloud-sample
  #        predicates:
  #        - RemoteAddr=192.168.126.218/24
