server:
  port: 9002

spring:
  application:
    name: spring-cloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8858
feign:
  sentinel:
    enabled: true
